apiVersion: v1
kind: Service
metadata:
  name: countryservice
  labels:
    name: country
spec:
  selector:
    country: finder
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008
  type: LoadBalancer