apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: countrybuilder
build:
  artifacts:
  - image: spring-boot-country-image
    jib: {}
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
    - k8s-configmap.yaml
    - k8s-service.yaml
